CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE Ammortamenti (
    IdAmmortamento       INTEGER        PRIMARY KEY AUTOINCREMENT,
    IdGruppoValoreInv    INT            NOT NULL,
    IdValoreInv          INT            NULL,
    Dal                  DATETIME       NOT NULL,
    Al                   DATETIME       NOT NULL,
    DOrdine              DECIMAL (18)   NOT NULL,
    StoricoIniCF         MONEY          NOT NULL,
    StoricoVarCF         MONEY          NOT NULL,
    StoricoCF            MONEY          NOT NULL,
    StoricoIniRP         MONEY          NOT NULL,
    StoricoVarRP         MONEY          NOT NULL,
    StoricoRP            MONEY          NOT NULL,
    StoricoIni           MONEY          NOT NULL,
    StoricoVar           MONEY          NOT NULL,
    Storico              MONEY          NOT NULL,
    QPersaIni            MONEY          NULL,
    QPersaVar            MONEY          NULL,
    QPersa               MONEY          NULL,
    RivalutazioneVarCF   MONEY          NOT NULL,
    RivalutazioneFondoCF MONEY          NOT NULL,
    RivalutazioneVarRP   MONEY          NOT NULL,
    RivalutazioneFondoRP MONEY          NOT NULL,
    RivalutazioneVar     MONEY          NOT NULL,
    RivalutazioneFondo   MONEY          NOT NULL,
    SvalutazioneVarCF    MONEY          NOT NULL,
    SvalutazioneFondoCF  MONEY          NOT NULL,
    SvalutazioneVarRP    MONEY          NOT NULL,
    SvalutazioneFondoRP  MONEY          NOT NULL,
    SvalutazioneVar      MONEY          NOT NULL,
    SvalutazioneFondo    MONEY          NOT NULL,
    Residuo01CF          MONEY          NOT NULL,
    Fondo01CF            MONEY          NOT NULL,
    Residuo01RP          MONEY          NOT NULL,
    Fondo01RP            MONEY          NOT NULL,
    Residuo01            MONEY          NOT NULL,
    Fondo01              MONEY          NOT NULL,
    QuotaCF              MONEY          NOT NULL,
    QuotaRP              MONEY          NOT NULL,
    QuotaTot             MONEY          NOT NULL,
    Residuo31CF          MONEY          NOT NULL,
    Fondo31CF            MONEY          NOT NULL,
    Residuo31RP          MONEY          NOT NULL,
    Fondo31RP            MONEY          NOT NULL,
    Residuo31            MONEY          NOT NULL,
    Fondo31              MONEY          NOT NULL,
    Aliquota             DECIMAL (6, 2) NOT NULL,
    IsPrimo              BIT            NOT NULL,
    IsUltimo             BIT            NOT NULL,
    IsVariazione         BIT            NOT NULL,
    CONSTRAINT FK_Ammortamenti_GruppiValoreInv FOREIGN KEY (
        IdGruppoValoreInv
    )
    REFERENCES GruppiValoreInv (IdGruppoValoreInv) ON DELETE CASCADE
                                                   ON UPDATE NO ACTION,
    CONSTRAINT FK_Ammortamenti_ValoriInv FOREIGN KEY (
        IdValoreInv
    )
    REFERENCES ValoriInv (IdValoreInv) ON DELETE NO ACTION
                                       ON UPDATE NO ACTION
);
CREATE TABLE Aree (
    IdArea               INTEGER   PRIMARY KEY AUTOINCREMENT,
    Denominazione        CHAR (60) NOT NULL,
    Codice               CHAR (10) NOT NULL,
    IsInUso              BIT       NULL,
    CodiceExt            CHAR (20) NULL,
    IdExt                CHAR (10) NULL,
    DTInserimento        DATETIME  NULL,
    IdUserInserimento    INT       NULL,
    DTUltimaModifica     DATETIME  NULL,
    IdUserUltimaModifica INT       NULL
);
CREATE TABLE BeniMobili (
    IdBeneMobile              INTEGER     PRIMARY KEY AUTOINCREMENT,
    IdSottoSpecie             INT         NULL,
    IdConservazione           INT         NULL,
    IdCondizioneGiuridica     INT         NULL,
    IdAspetto                 INT         NULL,
    TipoEtichetta             CHAR (1)    NOT NULL,
    Etichetta                 INT         NOT NULL,
    EtichettaOld              INT         NULL,
    LottoEtichetta            CHAR (10)   NULL,
    Descrizione               CHAR (255)  NULL,
    PercentualePossesso       FLOAT       NULL,
    DataInventario            DATETIME    NOT NULL,
    DataInserimento           DATETIME    NOT NULL,
    QuantitaLineare           FLOAT       NULL,
    Valore                    MONEY       NULL,
    ValoreBeneIntero          MONEY       NULL,
    isGies                    BIT         NOT NULL,
    isValorizzato             BIT         NOT NULL,
    DataValorizzazione        DATETIME    NULL,
    isPrimoTrasferimento      BIT         NULL,
    isEliminato               BIT         NOT NULL,
    isGruppo                  BIT         NOT NULL,
    isCapoGruppo              BIT         NOT NULL,
    IdCapoGruppo              INT         NULL,
    IsManutenzione            BIT         NOT NULL,
    IsOggettoManutenzione     BIT         NOT NULL,
    IdOggettoManutenzione     INT         NULL,
    ElementiGruppo            INT         NULL,
    HasTabAutomezzo           BIT         NULL,
    HasTabInformatica         BIT         NULL,
    HasTabArtistico           BIT         NULL,
    AmmortamentoEconomico     FLOAT       NULL,
    AmmortamentoFiscale       FLOAT       NULL,
    Matricola                 CHAR (30)   NULL,
    IsPropostaTrasf           BIT         NULL,
    IsAssente                 BIT         NULL,
    IsDaEliminare             BIT         NULL,
    HexRFidID                 CHAR (24)   NULL,
    HexRFidDATA               CHAR (16)   NULL,
    ValoreDaImputare          MONEY       NULL,
    ts                        BLOB        NULL,
    TipoEtichettaExt          CHAR (1)    NULL,
    EtichettaExt              CHAR (20)   NULL,
    CodiceExt                 CHAR (20)   NULL,
    IdExt                     CHAR (10)   NULL,
    StatoRevisione            SMALLINT    NULL,
    IdScritturaGiust          INT         NULL,
    IdGiustificativoGiust     INT         NULL,
    CIVAB                     CHAR (20)   NULL,
    DTInserimento             DATETIME    NULL,
    IdUserInserimento         INT         NULL,
    DTUltimaModifica          DATETIME    NULL,
    IdUserUltimaModifica      INT         NULL,
    Annotazioni               CHAR (1000) NULL,
    IsStampato                BIT         NOT NULL,
    IdTipoStatoInventario     INT         NOT NULL,
    RagioneMancataRilevazione CHAR (256)  NULL,
    IsDaAggregazione          BIT         NOT NULL
);
CREATE TABLE Categorie (
    IdCategoria                    INTEGER    PRIMARY KEY AUTOINCREMENT,
    IdPianoEcoStatoPatrimoniale    INT        NULL,
    Denominazione                  CHAR (256) NULL,
    Codice                         CHAR (10)  NOT NULL,
    AmmortamentoEco                FLOAT      NOT NULL,
    AmmortamentoFis                FLOAT      NOT NULL,
    IsDetrazioneFisApplicata       BIT        NOT NULL,
    IsUniversalita                 BIT        NOT NULL,
    PercentualeAmmEcoPA            FLOAT      NULL,
    GiornoPA                       INT        NULL,
    MesePA                         INT        NULL,
    CodiceExt                      CHAR (20)  NULL,
    IdExt                          CHAR (10)  NULL,
    DTInserimento                  DATETIME   NULL,
    IdUserInserimento              INT        NULL,
    DTUltimaModifica               DATETIME   NULL,
    IdUserUltimaModifica           INT        NULL,
    IdPianoEcoStatoPatrimonialeAcc INT        NULL,
    IsAPC                          BIT        NOT NULL,
    IsAB                           BIT        NOT NULL,
    CONSTRAINT FK_Categorie_PianiEcoStatiPatrimoniali FOREIGN KEY (
        IdPianoEcoStatoPatrimoniale
    )
    REFERENCES PianiEcoStatiPatrimoniali (IdPianoEcoStatoPatrimoniale) ON DELETE NO ACTION
                                                                       ON UPDATE NO ACTION
);
CREATE TABLE Causali (
    IdCausale            INTEGER   PRIMARY KEY AUTOINCREMENT,
    Descrizione          CHAR (40) NOT NULL,
    IsFinanziaria        BIT       NOT NULL,
    TipoCausale          CHAR (25) NOT NULL,
    IsDefault            BIT       NOT NULL,
    IsDefaultGies        BIT       NOT NULL,
    DTInserimento        DATETIME  NULL,
    IdUserInserimento    INT       NULL,
    DTUltimaModifica     DATETIME  NULL,
    IdUserUltimaModifica INT       NULL
);
CREATE TABLE CdRServizi (
    IdCdRServizio        INTEGER   PRIMARY KEY AUTOINCREMENT,
    IdArea               INT       NOT NULL,
    Denominazione        CHAR (60) NOT NULL,
    Codice               CHAR (10) NOT NULL,
    IsInUso              BIT       NULL,
    CodiceExt            CHAR (20) NULL,
    IdExt                CHAR (10) NULL,
    DTInserimento        DATETIME  NULL,
    IdUserInserimento    INT       NULL,
    DTUltimaModifica     DATETIME  NULL,
    IdUserUltimaModifica INT       NULL,
    CONSTRAINT FK_CdRServizi_Aree FOREIGN KEY (
        IdArea
    )
    REFERENCES Aree (IdArea) ON DELETE CASCADE
                             ON UPDATE NO ACTION
);
CREATE TABLE GruppiAmmortamento (
    IdGruppoAmmortamento        INTEGER   PRIMARY KEY AUTOINCREMENT,
    IdPianoEcoStatoPatrimoniale INT       NOT NULL,
    Descrizione                 CHAR (64) NOT NULL,
    IsDefault                   BIT       NOT NULL,
    IsDefaultModVal             BIT       NOT NULL,
    HasPrimoAnnoAmm             BIT       NOT NULL,
    QuotaAmmPA                  FLOAT     NOT NULL,
    CodiceAmmortamento          CHAR (20) NULL,
    DTInserimento               DATETIME  NULL,
    IdUserInserimento           INT       NULL,
    DTUltimaModifica            DATETIME  NULL,
    IdUserUltimaModifica        INT       NULL,
    CONSTRAINT FK_GruppiAmmortamento_PianiEcoStatiPatrimoniali FOREIGN KEY (
        IdPianoEcoStatoPatrimoniale
    )
    REFERENCES PianiEcoStatiPatrimoniali (IdPianoEcoStatoPatrimoniale) ON DELETE CASCADE
                                                                       ON UPDATE NO ACTION
);
CREATE TABLE Locali (
    IdLocale             INTEGER   PRIMARY KEY AUTOINCREMENT,
    IdEdificio           INT       NOT NULL,
    IdUI                 INT       NULL,
    Denominazione        CHAR (60) NOT NULL,
    Piano                CHAR (5)  NULL,
    Interno              CHAR (10) NULL,
    Codice               CHAR (20) NULL,
    IsAttivo             BIT       NOT NULL,
    CodiceRFid           INT       NULL,
    HexCodiceRFid        CHAR (6)  NULL,
    CodiceExt            CHAR (20) NULL,
    IdExt                CHAR (10) NULL,
    Etichetta            INT       NULL,
    HexRFidID            CHAR (24) NULL,
    DTInserimento        DATETIME  NULL,
    IdUserInserimento    INT       NULL,
    DTUltimaModifica     DATETIME  NULL,
    IdUserUltimaModifica INT       NULL,
    CONSTRAINT FK_Locali_Edifici FOREIGN KEY (
        IdEdificio
    )
    REFERENCES Edifici (IdEdificio) ON DELETE CASCADE
                                    ON UPDATE NO ACTION
);
CREATE TABLE MobiliLocali (
    IdMobileLocale       INTEGER   PRIMARY KEY AUTOINCREMENT,
    IdBeneMobile         INT       NOT NULL,
    IdLocale             INT       NULL,
    Dal                  DATETIME  NULL,
    Al                   DATETIME  NULL,
    IsUltimo             BIT       NOT NULL,
    NoteTrasferimento    CHAR (64) NULL,
    ts                   BLOB      NULL,
    DTInserimento        DATETIME  NULL,
    IdUserInserimento    INT       NULL,
    DTUltimaModifica     DATETIME  NULL,
    IdUserUltimaModifica INT       NULL,
    CONSTRAINT FK_MobiliLocali_BeniMobili FOREIGN KEY (
        IdBeneMobile
    )
    REFERENCES BeniMobili (IdBeneMobile) ON DELETE CASCADE
                                         ON UPDATE NO ACTION,
    CONSTRAINT FK_MobiliLocali_Locali FOREIGN KEY (
        IdLocale
    )
    REFERENCES Locali (IdLocale) ON DELETE CASCADE
                                 ON UPDATE NO ACTION
);
CREATE TABLE MobiliSottoSpeci (
    IdMobileSottoSpecie  INTEGER  PRIMARY KEY AUTOINCREMENT,
    IdBeneMobile         INT      NOT NULL,
    IdSottoSpecie        INT      NOT NULL,
    Dal                  DATETIME NOT NULL,
    Al                   DATETIME NULL,
    IsUltimo             BIT      NOT NULL,
    DTInserimento        DATETIME NULL,
    IdUserInserimento    INT      NULL,
    DTUltimaModifica     DATETIME NULL,
    IdUserUltimaModifica INT      NULL,
    CONSTRAINT FK_MobiliSottoSpeci_IdBM FOREIGN KEY (
        IdBeneMobile
    )
    REFERENCES BeniMobili (IdBeneMobile) ON DELETE CASCADE
                                         ON UPDATE NO ACTION,
    CONSTRAINT FK_MobiliSottoSpeci_IdSS FOREIGN KEY (
        IdSottoSpecie
    )
    REFERENCES SottoSpeci (IdSottoSpecie) ON DELETE NO ACTION
                                          ON UPDATE NO ACTION
);
CREATE TABLE PianiEcoStatiPatrimoniali (
    IdPianoEcoStatoPatrimoniale INTEGER    PRIMARY KEY AUTOINCREMENT,
    IdComponenteCESP            INT        NULL,
    Descrizione                 CHAR (256) NOT NULL,
    Codice                      CHAR (30)  NULL,
    IsPianoEconomicoDare        BIT        NOT NULL,
    IsPianoEconomicoAvere       BIT        NOT NULL,
    IsStatoPatrimonialeDare     BIT        NOT NULL,
    IsStatoPatrimonialeAvere    BIT        NOT NULL,
    IsContoRiepilogativo        BIT        NOT NULL,
    HasFondo                    BIT        NOT NULL,
    IsFondo                     BIT        NOT NULL,
    IsAmmFondo                  BIT        NOT NULL,
    IsIVA                       BIT        NOT NULL,
    IsStatoPatrimonialeBM       BIT        NOT NULL,
    IsStatoPatrimonialeIM       BIT        NOT NULL,
    IsStatoPatrimonialeIC       BIT        NOT NULL,
    IsDemanialeConto            BIT        NOT NULL,
    IsLeasingConto              BIT        NOT NULL,
    IsAltriConto                BIT        NOT NULL,
    IsChiusura                  BIT        NOT NULL,
    IsApertura                  BIT        NOT NULL,
    IsProfittiPerdite           BIT        NOT NULL,
    IsUtilePerdita              BIT        NOT NULL,
    IsStatoPatrimonialeIIM      BIT        NOT NULL,
    IsSterilizzaValore          BIT        NOT NULL,
    IsSterilizzaRiserva         BIT        NOT NULL,
    IsSterilizzaSopravvenienza  BIT        NOT NULL,
    IsSterilizzaInsussistenza   BIT        NOT NULL,
    CodiceARCONET               CHAR (30)  NULL,
    IsCO                        BIT        NOT NULL,
    DTInserimento               DATETIME   NULL,
    IdUserInserimento           INT        NULL,
    DTUltimaModifica            DATETIME   NULL,
    IdUserUltimaModifica        INT        NULL,
    IsCredito                   BIT        NOT NULL,
    IsSterilizzaDotazione       BIT        NOT NULL,
    IsSterilizzaDevoluzione     BIT        NOT NULL,
    IsAccontoRicevuto           BIT        NOT NULL,
    IsAccrual                   BIT        NOT NULL,
    CondizioneGiuridica         CHAR (1)   NULL,
    IsAPC                       BIT        NOT NULL,
    IsII                        BIT        NOT NULL,
    IsAB                        BIT        NOT NULL,
    IsSC                        BIT        NOT NULL,
    IsLF                        BIT        NOT NULL,
    Segmento                    CHAR (2)   NULL,
    LivelloITAS                 CHAR (5)   NULL,
    IsUltimoLivello             BIT        NOT NULL,
    VoceSchemaBil               CHAR (256) NULL,
    IsDebito                    BIT        NOT NULL
);
CREATE TABLE SchedePatrimoniali (
    IdSchedaPatrimoniale          INTEGER     PRIMARY KEY AUTOINCREMENT,
    IdTipoSchedaPatrimoniale      INT         NOT NULL,
    IdTerreno                     INT         NULL,
    IdFabbricato                  INT         NULL,
    IdInfrastruttura              INT         NULL,
    IdImmobilizzazioneImmateriale INT         NULL,
    IdDirittoReale                INT         NULL,
    IdCompendio                   INT         NULL,
    Descrizione                   CHAR (120)  NULL,
    SchedaDal                     DATETIME    NOT NULL,
    SchedaAl                      DATETIME    NULL,
    PercentualePossesso           FLOAT       NULL,
    InizioContabile               DATETIME    NULL,
    FineContabile                 DATETIME    NULL,
    IsSchedaAttiva                BIT         NOT NULL,
    IsPrimaScheda                 BIT         NOT NULL,
    IsAlienata                    BIT         NOT NULL,
    IsPossibilePertinenza         BIT         NOT NULL,
    IsPossibilePertinente         BIT         NOT NULL,
    IsPertinenza                  BIT         NOT NULL,
    IsPertinente                  BIT         NOT NULL,
    IsICI                         BIT         NULL,
    CodiceUIInterno               CHAR (30)   NULL,
    Annotazioni                   CHAR (1000) NULL,
    IdNodoCatastale               INT         NULL,
    UToponimo                     CHAR (30)   NULL,
    UAnnoInventario               SMALLINT    NULL,
    IdGestione                    INT         NULL,
    UIdTipoDestinazioneUI         INT         NULL,
    USuperficiemq                 FLOAT       NULL,
    UAltezzaML                    FLOAT       NULL,
    UUsoEsclusivomq               FLOAT       NULL,
    UCubaturamq                   FLOAT       NULL,
    UBalconimq                    FLOAT       NULL,
    UPostoAutomq                  FLOAT       NULL,
    URimessamq                    FLOAT       NULL,
    UCantinoleMQ                  FLOAT       NULL,
    ULocaliCaldaiaMQ              FLOAT       NULL,
    UStenditoiMQ                  FLOAT       NULL,
    USpaziApertiComuniMQ          FLOAT       NULL,
    UGiardiniMQ                   FLOAT       NULL,
    USuperficieCopertaMQ          FLOAT       NULL,
    USuperficieScopertaMQ         FLOAT       NULL,
    UIdTipoImpiantoElettrico      INT         NULL,
    UIdTipoSCIE                   INT         NULL,
    UIdTipoImpiantoScarico        INT         NULL,
    UIdTipoSCIS                   INT         NULL,
    UIdTipoImpiantoCarico         INT         NULL,
    UIdTipoSCIC                   INT         NULL,
    UIdTipoImpiantoRiscaldamento  INT         NULL,
    UIdTipoSCIR                   INT         NULL,
    UIdTipoCombustibile           INT         NULL,
    UIdTipoPavimento              INT         NULL,
    UIdTipoSCPA                   INT         NULL,
    UIdTipoRivestimento           INT         NULL,
    UIdTipoSCRI                   INT         NULL,
    UAnnoCostruzione              SMALLINT    NULL,
    UAnnoRistrutturazione         SMALLINT    NULL,
    UVincoli                      CHAR (30)   NULL,
    UProvenienza                  CHAR (30)   NULL,
    UStimaMercato                 MONEY       NULL,
    UCostoCostruzione             MONEY       NULL,
    UDataStima                    DATETIME    NULL,
    UDataCostoCostruzione         DATETIME    NULL,
    TDestPRGV                     CHAR (30)   NULL,
    TIdDestPRGV                   INT         NULL,
    TProvenienza                  CHAR (30)   NULL,
    TIdProvenienza                INT         NULL,
    TPartProv                     CHAR (100)  NULL,
    TAnnoInventario               SMALLINT    NULL,
    TValoreMercato                MONEY       NULL,
    TDataValoreMercato            DATETIME    NULL,
    TPercentualeProprieta         FLOAT       NULL,
    TSuperficieReale              FLOAT       NULL,
    SUbicazione                   CHAR (40)   NULL,
    STipoStrada                   CHAR (15)   NULL,
    SCategoria                    CHAR (25)   NULL,
    SQualitaFondoStradale         CHAR (20)   NULL,
    SStatoManto                   CHAR (20)   NULL,
    SLunghezza                    FLOAT       NULL,
    SLarghezza                    FLOAT       NULL,
    SAmpiezza                     FLOAT       NULL,
    SNumeroCorsie                 SMALLINT    NULL,
    SValoreStrada                 MONEY       NULL,
    SAnnoCostruzione              SMALLINT    NULL,
    SDaA                          CHAR (255)  NULL,
    SAlberaturaSegnaletica        CHAR (255)  NULL,
    SIllAppesa                    INT         NULL,
    SIllPalo                      INT         NULL,
    SIllPalo450                   INT         NULL,
    SIllPalo800                   INT         NULL,
    SIllPalo1200                  INT         NULL,
    SIllPaloOltre                 INT         NULL,
    SValoreIlluminazione          MONEY       NULL,
    FTratta                       CHAR (20)   NULL,
    FMateriale                    CHAR (20)   NULL,
    FConservazione                CHAR (20)   NULL,
    FTipoFogna                    CHAR (10)   NULL,
    FTrasporto                    CHAR (10)   NULL,
    FDiametro                     FLOAT       NULL,
    FLunghezza                    FLOAT       NULL,
    FValoreTratta                 MONEY       NULL,
    FAnnoCostruzione              SMALLINT    NULL,
    FLocalizzazione               CHAR (255)  NULL,
    FUtenzeImmissione             CHAR (255)  NULL,
    ATratta                       CHAR (20)   NULL,
    ATipoAcquedotto               CHAR (20)   NULL,
    AConservazione                CHAR (20)   NULL,
    ADiametro                     FLOAT       NULL,
    ALunghezza                    FLOAT       NULL,
    ACostoCostruzione             MONEY       NULL,
    AAnnoCostruzione              SMALLINT    NULL,
    ALocalizzazione               CHAR (255)  NULL,
    APozziSorgenti                CHAR (255)  NULL,
    ADepositiTorri                CHAR (255)  NULL,
    GTratta                       CHAR (20)   NULL,
    GTipoGasdotto                 CHAR (20)   NULL,
    GConservazione                CHAR (20)   NULL,
    GValoreGasdotto               MONEY       NULL,
    GAnnoCostruzione              SMALLINT    NULL,
    GLunghezza                    FLOAT       NULL,
    GDiametro                     FLOAT       NULL,
    GLocalizzazione               CHAR (255)  NULL,
    GUtenzeServiteCabine          CHAR (255)  NULL,
    DVia                          CHAR (60)   NULL,
    DUbicazione                   CHAR (40)   NULL,
    DCatasto                      CHAR (40)   NULL,
    DScadenza                     DATETIME    NULL,
    DSuperficie                   FLOAT       NULL,
    DIdTipoDiritto                INT         NULL,
    Segnatura                     CHAR (2)    NULL,
    CodiceExt                     CHAR (20)   NULL,
    IdExt                         CHAR (10)   NULL,
    DIdNodoDominante              INT         NULL,
    ILunghezza                    FLOAT       NULL,
    IMateriale                    CHAR (128)  NULL,
    ILocalizzazione               CHAR (256)  NULL,
    IDaA                          CHAR (256)  NULL,
    IAnnoCostruzione              SMALLINT    NULL,
    IsEsclusoMEF                  BIT         NULL,
    UAltezzaLorda                 FLOAT       NULL,
    UVolumeLordo                  FLOAT       NULL,
    USuperficieCalpestabile       FLOAT       NULL,
    USuperficieCommerciale        FLOAT       NULL,
    CodiceAnagrafica              CHAR (20)   NULL,
    DTInserimento                 DATETIME    NULL,
    IdUserInserimento             INT         NULL,
    DTUltimaModifica              DATETIME    NULL,
    IdUserUltimaModifica          INT         NULL,
    USuperficieLottoMQ            FLOAT       NULL,
    IdTipoMisurazioneSup          INT         NULL,
    UIdTipoMisurazioneLotto       INT         NULL,
    USuperficieNettaMQ            FLOAT       NULL,
    MSuperficie                   FLOAT       NULL,
    CodiceAnagraficaSub           INT         NULL,
    IdPartitaPatrimoniale         INT         NULL,
    IdTipoInventario              INT         NULL,
    IdStatoInventario             INT         NULL,
    IdBeneMEF                     INT         NULL,
    PLuci                         FLOAT       NULL,
    PLunghezza                    FLOAT       NULL,
    PLarghezza                    FLOAT       NULL,
    PMetrilineari                 FLOAT       NULL,
    PImpalcoMQ                    FLOAT       NULL,
    PNumeroCampate                INT         NULL,
    PNumeroPile                   INT         NULL,
    PNumeroSpalle                 INT         NULL,
    PLimiteH                      FLOAT       NULL,
    PIsBarriere                   BIT         NULL,
    PIsDaIspezionare              BIT         NULL,
    PIdCategoriaPonte             INT         NULL,
    PIdTipologiaPonte             INT         NULL,
    PIdMaterialePonte             INT         NULL,
    PIdInterventoPonte            INT         NULL,
    PIdSchemaStaticoPonte         INT         NULL,
    UIsConfiscatoCriminalitaOrg   BIT         NULL,
    TIsConfiscatoCriminalitaOrg   BIT         NULL,
    TIdDirittoGravanteBene        INT         NULL,
    IdTipoStatoInventario         INT         NOT NULL,
    RagioneMancataRilevazione     CHAR (256)  NULL,
    IsDaAggregazione              BIT         NOT NULL
);
CREATE TABLE SottoSpeci (
    IdSottoSpecie                INTEGER      PRIMARY KEY AUTOINCREMENT,
    IdSpecie                     INT          NOT NULL,
    Denominazione                CHAR (50)    NOT NULL,
    Codice                       CHAR (10)    NULL,
    Prezzo                       MONEY        NOT NULL,
    IsPrezzoUA                   BIT          NOT NULL,
    UnitaMisura                  CHAR (10)    NULL,
    IsBeneAssociatoValorizzabile BIT          NOT NULL,
    CodiceExt                    VARCHAR (64) NULL,
    IdExt                        CHAR (10)    NULL,
    IsAttiva                     BIT          NULL,
    DTInserimento                DATETIME     NULL,
    IdUserInserimento            INT          NULL,
    DTUltimaModifica             DATETIME     NULL,
    IdUserUltimaModifica         INT          NULL,
    CONSTRAINT FK_SottoSpeci_Speci FOREIGN KEY (
        IdSpecie
    )
    REFERENCES Speci (IdSpecie) ON DELETE CASCADE
                                ON UPDATE NO ACTION
);
CREATE TABLE Speci (
    IdSpecie             INTEGER   PRIMARY KEY AUTOINCREMENT,
    IdCategoria          INT       NOT NULL,
    Denominazione        CHAR (50) NOT NULL,
    Codice               CHAR (20) NULL,
    CodiceExt            CHAR (20) NULL,
    IdExt                CHAR (10) NULL,
    DTInserimento        DATETIME  NULL,
    IdUserInserimento    INT       NULL,
    DTUltimaModifica     DATETIME  NULL,
    IdUserUltimaModifica INT       NULL,
    CONSTRAINT FK_Speci_Categorie FOREIGN KEY (
        IdCategoria
    )
    REFERENCES Categorie (IdCategoria) ON DELETE CASCADE
                                       ON UPDATE NO ACTION
);
CREATE TABLE TipiValoreInv (
    IdTipoValoreInv         INTEGER   PRIMARY KEY AUTOINCREMENT,
    Descrizione             CHAR (75) NOT NULL,
    IsPrimaApertura         BIT       NOT NULL,
    IsRivalutazioneVal      BIT       NOT NULL,
    IsRivalutazioneValFondo BIT       NOT NULL,
    IsRivalutazionePatr     BIT       NOT NULL,
    IsSvalutazioneVal       BIT       NOT NULL,
    IsSvalutazionePatr      BIT       NOT NULL,
    IsScorporo              BIT       NOT NULL,
    IsScaricoDemolizione    BIT       NOT NULL,
    IsMutazione             BIT       NOT NULL,
    IsChiusuraIIC           BIT       NOT NULL,
    IsPrimoInserimento      BIT       NOT NULL,
    IsDaMastro              BIT       NOT NULL,
    IsRivalutazione         BIT       NOT NULL,
    IsSvalutazione          BIT       NOT NULL,
    IsScarico               BIT       NOT NULL,
    IsIIC                   BIT       NOT NULL,
    IsRiporto               BIT       NOT NULL,
    IsDaStima               BIT       NOT NULL,
    IsRivalutazioneConf     BIT       NOT NULL,
    IsSvalutazioneConf      BIT       NOT NULL,
    IsRivalutazioneDotaz    BIT       NOT NULL,
    IsSvalutazioneDotaz     BIT       NOT NULL,
    IsRivalutazioneDevoluz  BIT       NOT NULL,
    IsSvalutazioneSval      BIT       NOT NULL,
    IsSvalutazioneProrata   BIT       NOT NULL,
    IsRivalutazioneProrata  BIT       NOT NULL,
    IsChiusuraVIC           BIT       NOT NULL,
    IsRettificaAcconto      BIT       NOT NULL,
    IsRettificaSAL          BIT       NOT NULL,
    IsScorporoSP            BIT       NOT NULL,
    IsScorporoGVI           BIT       NOT NULL,
    IsVenditaGS             BIT       NOT NULL,
    IsRiclassificazione     BIT       NOT NULL
);
CREATE TABLE ValoriInv (
    IdValoreInv               INTEGER      PRIMARY KEY AUTOINCREMENT,
    IdGruppoValoreInv         INT          NOT NULL,
    IdTipoValoreInv           INT          NOT NULL,
    DataContabile             DATETIME     NOT NULL,
    NumOrdine                 INT          NOT NULL,
    DOrdine                   DECIMAL (18) NOT NULL,
    Importo                   MONEY        NOT NULL,
    ImportoRisProprie         MONEY        NOT NULL,
    ImportoConferimento       MONEY        NOT NULL,
    IsInserimentoConFondo     BIT          NOT NULL,
    ImportoResiduo            MONEY        NOT NULL,
    ImportoFondo              MONEY        NOT NULL,
    ImportoResiduoRP          MONEY        NOT NULL,
    ImportoFondoRP            MONEY        NOT NULL,
    ImportoResiduoCF          MONEY        NOT NULL,
    ImportoFondoCF            MONEY        NOT NULL,
    QuotaPersa                MONEY        NULL,
    IsSvalutazione            BIT          NOT NULL,
    IsRivalutazione           BIT          NOT NULL,
    FineContabile             DATETIME     NULL,
    IsAttivo                  BIT          NOT NULL,
    IdImmobilizzazioneInCorso INT          NULL,
    IdValoreInvIIC            INT          NULL,
    Descrizione               CHAR (256)   NULL,
    ProgressivoValoreCespite  INT          NULL,
    IsAppoggio                BIT          NULL,
    IdValoreInvAppoggio       INT          NULL,
    IsSvalutazioneRP          BIT          NULL,
    DTInserimento             DATETIME     NULL,
    IdUserInserimento         INT          NULL,
    DTUltimaModifica          DATETIME     NULL,
    IdUserUltimaModifica      INT          NULL,
    IdVenditaInCorso          INT          NULL,
    IsSvalutazioneConf        BIT          NOT NULL,
    CONSTRAINT FK_ValoriInv_GruppiValoreInv FOREIGN KEY (
        IdGruppoValoreInv
    )
    REFERENCES GruppiValoreInv (IdGruppoValoreInv) ON DELETE CASCADE
                                                   ON UPDATE NO ACTION,
    CONSTRAINT FK_TipiValoreInv_ValoriInv FOREIGN KEY (
        IdTipoValoreInv
    )
    REFERENCES TipiValoreInv (IdTipoValoreInv) ON DELETE CASCADE
                                               ON UPDATE NO ACTION
);
CREATE TABLE VMValoriInv (
    IdVMValoreInv        INTEGER PRIMARY KEY AUTOINCREMENT,
    IdVoceMastrino       INT     NOT NULL,
    IdValoreInv          INT     NOT NULL,
    Importo              MONEY   NOT NULL,
    IsValoreStorico      BIT     NULL,
    IsValoreFondo        BIT     NULL,
    IsPrimaApertura      BIT     NULL,
    IsValorePlusV        BIT     NULL,
    IsValoreMinusV       BIT     NULL,
    IsValoreCredito      BIT     NULL,
    IsValoreRiserve      BIT     NULL,
    IsValoreInsussAtt    BIT     NULL,
    IsValoreSopravvAtt   BIT     NULL,
    IsValoreDotazione    BIT     NOT NULL,
    IsValoreDevoluzione  BIT     NOT NULL,
    IsValoreSvalutazione BIT     NOT NULL,
    IsValoreIva          BIT     NOT NULL,
    IsValoreAccontoRic   BIT     NOT NULL,
    CONSTRAINT FK_VMValoriInv_ValoriInv FOREIGN KEY (
        IdValoreInv
    )
    REFERENCES ValoriInv (IdValoreInv) ON DELETE NO ACTION
                                       ON UPDATE NO ACTION,
    CONSTRAINT FK_VMValoriInv_VociMastrino FOREIGN KEY (
        IdVoceMastrino
    )
    REFERENCES VociMastrino (IdVoceMastrino) ON DELETE CASCADE
                                             ON UPDATE NO ACTION
);
CREATE TABLE VociMastrino (
    IdVoceMastrino              INTEGER    PRIMARY KEY AUTOINCREMENT,
    IdPianoEcoStatoPatrimoniale INT        NOT NULL,
    IdScrittura                 INT        NOT NULL,
    Descrizione                 CHAR (256) NULL,
    IsDare                      BIT        NOT NULL,
    ImportoDare                 MONEY      NOT NULL,
    IsAvere                     BIT        NOT NULL,
    ImportoAvere                MONEY      NOT NULL,
    IsPrimaApertura             BIT        NOT NULL,
    IsApertura                  BIT        NOT NULL,
    IsChiusura                  BIT        NOT NULL,
    IsUtilePerditaEser          BIT        NOT NULL,
    IsOrdinaria                 BIT        NOT NULL,
    Codice                      CHAR (30)  NULL,
    IdValoreInvAppoggio         INT        NULL,
    IdValoreInvAppoggioBis      INT        NULL,
    IdProgramma                 INT        NULL,
    DTInserimento               DATETIME   NULL,
    IdUserInserimento           INT        NULL,
    DTUltimaModifica            DATETIME   NULL,
    IdUserUltimaModifica        INT        NULL,
    IdSpCesp                    INT        NULL,
    IdVmPadreProrata            INT        NULL,
    HasProrata                  BIT        NULL,
    IsProrata                   BIT        NULL,
    IsGenerata                  BIT        NULL,
    OrdineVM                    INT        NULL,
    IdVmPadre                   INT        NULL,
    IdMastroVoceMastrino        INT        NULL
);
CREATE TABLE GruppiValoreInv (
    IdGruppoValoreInv         INTEGER    PRIMARY KEY AUTOINCREMENT,
    IdGruppoAmmortamento      INT        NOT NULL,
    IdBeneMobile              INT        NULL,
    IdSchedaPatrimoniale      INT        NULL,
    IdImmobilizzazioneInCorso INT        NULL,
    Descrizione               CHAR (256) NOT NULL,
    TipoRipartizione          INT        NULL,
    TipoCalcolo               SMALLINT   NOT NULL,
    DescTipoCalcolo           CHAR (22)  NOT NULL,
    IsAttivo                  BIT        NOT NULL,
    IdGruppoValoreInvOld      INT        NULL,
    IdGruppoValoreInvAppoggio INT        NULL,
    IdTokenAppoggio           INT        NULL,
    DTInserimento             DATETIME   NULL,
    IdUserInserimento         INT        NULL,
    DTUltimaModifica          DATETIME   NULL,
    IdUserUltimaModifica      INT        NULL,
    DescrizioneFin            CHAR (150) NULL,
    IdVenditaInCorso          INT        NULL,
    IsPrimaAdozione           BIT        NOT NULL,
    IsAttivitaRilevante       BIT        NOT NULL,
    CONSTRAINT FK_GruppiValoreInv_BeniMobili FOREIGN KEY (
        IdBeneMobile
    )
    REFERENCES BeniMobili (IdBeneMobile) ON DELETE CASCADE
                                         ON UPDATE NO ACTION,
    CONSTRAINT FK_GruppiValoreInv_GruppiAmmortamento FOREIGN KEY (
        IdGruppoAmmortamento
    )
    REFERENCES GruppiAmmortamento (IdGruppoAmmortamento) ON DELETE CASCADE
                                                         ON UPDATE NO ACTION,
    CONSTRAINT FK_GruppiValoreInv_IdOld FOREIGN KEY (
        IdGruppoValoreInvOld
    )
    REFERENCES GruppiValoreInv (IdGruppoValoreInv) ON DELETE NO ACTION
                                                   ON UPDATE NO ACTION,
    CONSTRAINT FK_GruppiValoreInv_SchedePatrimoniali FOREIGN KEY (
        IdSchedaPatrimoniale
    )
    REFERENCES SchedePatrimoniali (IdSchedaPatrimoniale) ON DELETE CASCADE
                                                         ON UPDATE NO ACTION
);
CREATE TABLE CondizioniGiuridiche (
  IdCondizioneGiuridica   INTEGER PRIMARY KEY AUTOINCREMENT,
  Descrizione             TEXT NOT NULL,
  isDefault               INTEGER NOT NULL,         -- 0/1
  Codice                  TEXT,
  CodiceExt               TEXT,
  IdExt                   TEXT,
  DTInserimento           TEXT,                     -- ISO-8601: 'YYYY-MM-DD HH:MM:SS'
  IdUserInserimento       INTEGER,
  DTUltimaModifica        TEXT,
  IdUserUltimaModifica    INTEGER
);
CREATE TABLE Conservazioni (
  IdConservazione         INTEGER PRIMARY KEY AUTOINCREMENT,
  Descrizione             TEXT NOT NULL,
  Coeff                   REAL NOT NULL,
  isDefault               INTEGER NOT NULL,         -- 0/1
  Codice                  TEXT,
  CodiceExt               TEXT,
  IdExt                   TEXT,
  DTInserimento           TEXT,
  IdUserInserimento       INTEGER,
  DTUltimaModifica        TEXT,
  IdUserUltimaModifica    INTEGER
);
CREATE TABLE Aspetti (
  IdAspetto               INTEGER PRIMARY KEY AUTOINCREMENT,
  Descrizione             TEXT NOT NULL,
  isDefault               INTEGER NOT NULL,         -- 0/1
  Codice                  TEXT,
  CodiceExt               TEXT,
  IdExt                   TEXT,
  DTInserimento           TEXT,
  IdUserInserimento       INTEGER,
  DTUltimaModifica        TEXT,
  IdUserUltimaModifica    INTEGER
);
CREATE TABLE CdGCdC (IdCdGCdC INTEGER PRIMARY KEY AUTOINCREMENT, IdCdRServizio INT NOT NULL, IdFunzioneServizio INT NULL, IdPegCdC INT NULL, Denominazione CHAR (60) NOT NULL, Codice CHAR (10) NOT NULL, IsInUso BIT NULL, CodiceExt CHAR (20) NULL, IdExt CHAR (10) NULL, DTInserimento DATETIME NULL, IdUserInserimento INT NULL, DTUltimaModifica DATETIME NULL, IdUserUltimaModifica INT NULL, CONSTRAINT FK_CdGCdC_CdRServizi FOREIGN KEY (IdCdRServizio) REFERENCES CdRServizi (IdCdRServizio) ON DELETE CASCADE ON UPDATE NO ACTION);
CREATE TABLE Edifici (IdEdificio INTEGER PRIMARY KEY AUTOINCREMENT, Denominazione CHAR (60) NOT NULL, Via CHAR (35) NOT NULL, Civici CHAR (20) NOT NULL, Localita CHAR (35) NULL, Comune CHAR (100) NULL, Provincia CHAR (3) NOT NULL, IsAttivo BIT NOT NULL, Codice CHAR (10) NULL, CodiceExt CHAR (20) NULL, IdExt CHAR (10) NULL, DTInserimento DATETIME NULL, IdUserInserimento INT NULL, DTUltimaModifica DATETIME NULL, IdUserUltimaModifica INT NULL, IdTopoComune INT NULL);
CREATE TABLE MobiliCdGCdC (IdMobileCdGCdC INTEGER PRIMARY KEY AUTOINCREMENT, IdBeneMobile INT NOT NULL, IdCdGCdC INT NULL, IdCausale INT NOT NULL, Dal DATETIME NULL, Al DATETIME NULL, IsUltimo BIT NOT NULL, NoteTrasferimento CHAR (64) NULL, IsCaricoSubAvv BIT NULL, IdVerbaleCaSu INT NULL, IsScaricoSubAvv BIT NULL, IdVerbaleScSu INT NULL, IsCaricoConAvv BIT NULL, IdVerbaleCaCo INT NULL, IsScaricoConAvv BIT NULL, IdVerbaleScCo INT NULL, ts BLOB NULL, DTInserimento DATETIME NULL, IdUserInserimento INT NULL, DTUltimaModifica DATETIME NULL, IdUserUltimaModifica INT NULL, CONSTRAINT FK_MobiliCdGCdC_BeniMobili FOREIGN KEY (IdBeneMobile) REFERENCES BeniMobili (IdBeneMobile) ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT FK_MobiliCdGCdC_Causali FOREIGN KEY (IdCausale) REFERENCES Causali (IdCausale) ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT FK_MobiliCdGCdC_CdGCdC FOREIGN KEY (IdCdGCdC) REFERENCES CdGCdC (IdCdGCdC) ON DELETE CASCADE ON UPDATE NO ACTION);