import json
import os
import re
import torch
from typing import List, Set, Dict, Optional
from pydantic import BaseModel, Field
from langchain_core.tools import tool
from langchain_chroma import Chroma
import pickle
from langchain_classic.retrievers import EnsembleRetriever
from langchain_community.retrievers import BM25Retriever
from src.models import SearchSchemaInput
from src.embedding_factory import get_shared_embedding_function
from src.utils import get_canonical_name
from src.config import CHROMA_PATH, COLLECTION_NAME, BM25_PATH, VALUE_COLLECTION_NAME

warnings.filterwarnings("ignore", message=".*PydanticSerializationUnexpectedValue.*")


DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"🔌 Loading Embeddings on: {DEVICE}")

# Cache the embedding function globally for the module
EMBEDDING_FUNCTION = get_shared_embedding_function()

# Initializes and returns the Chroma vector store connection
def get_vectorstore() -> Chroma:
    return Chroma(
        persist_directory=CHROMA_PATH,
        embedding_function=EMBEDDING_FUNCTION,
        collection_name=COLLECTION_NAME
    )

# Hybrid parser combining JSON and regex implicit FKs
def _parse_and_add_to_map(raw_json_str: str, schema_map: Dict[str, dict], tables_to_fetch: Optional[Set[str]] = None) -> None:
    """
    Instant parser: the data has already been cleaned, formatted and “streamlined” 
    during ingestion. We just need to load it and map the FKs.
    """
    try:
        full_data = json.loads(raw_json_str)
        
        tbl_name = full_data.get("table_name")
        if not tbl_name: 
            return

        tbl_canon = get_canonical_name(str(tbl_name))
        
        # Avoid duplicates
        if tbl_canon in schema_map: 
            return

        # Populate the set of tables to be expanded using Foreign Keys.
        if tables_to_fetch is not None:
            fk_list = full_data.get("foreign_keys", [])
            for fk in fk_list:
                target_canon = fk.get("to_table_canonical")
                if target_canon:
                    tables_to_fetch.add(target_canon)

        # Save the ‘Slim Scheme’ directly 
        schema_map[tbl_canon] = full_data

    except Exception as e:
        print(f"Error parsing json in _parse_and_add_to_map: {e}")

# Wrapper to process a single Chroma document and its metadata
def _process_single_doc(doc, schema_map: Dict[str, dict], tables_to_fetch: Set[str]) -> None:
    raw_json = doc.metadata.get("table_schema")
    if raw_json:
        _parse_and_add_to_map(raw_json, schema_map, tables_to_fetch)

# Hybrid retrieval tool combining semantic search and regex fk expansion
@tool("search_schema_tool", args_schema=SearchSchemaInput)
def search_schema_tool(query: str, k: int = 6) -> str: #mettere k = 7 con Llama 70B per evitare di sforare i token 
    """Ricerca lo schema del database utilizzando ricerca semantica ibrida e foreign keys."""
    empty_json = json.dumps([], indent=2)

    try:
        vectorstore = get_vectorstore()
        collection = vectorstore._collection
        
        total_docs = collection.count()
        actual_k = min(k, total_docs) if total_docs > 0 else k

        chroma_retriever = vectorstore.as_retriever(search_kwargs={"k": actual_k})
        
        try:
            with open(BM25_PATH, 'rb') as f:
                bm25_retriever = pickle.load(f)
            bm25_retriever.k = actual_k
            
            # Reciprocal Rank Fusion (RRF): combines the two retrievers. 
            # The weights decide which one ‘counts’ more. 0.5/0.5 is the balanced default.
            retriever = EnsembleRetriever(
                retrievers=[bm25_retriever, chroma_retriever], 
                weights=[0.4, 0.6]
            )
            print(f"ibrido (BM25 + Dense RRF) attivo (k={actual_k}).")
        except Exception as e:
            print(f"⚠️ Indice BM25 non trovato. Fallback su Chroma puro. ({e})")
            retriever = chroma_retriever

        # Execution of the combined retrieval
        anchor_results = retriever.invoke(query)
        
        # Remove any duplicates generated by merging
        # (EnsembleRetriever usually merges them, check for unique IDs to be on the safe side)
        unique_results = {doc.metadata.get("canonical_name", "unknown"): doc for doc in anchor_results}
        anchor_results = list(unique_results.values())[:actual_k]

        final_schema_map: Dict[str, dict] = {}
        tables_to_fetch_names: Set[str] = set()

        anchor_names = [doc.metadata.get("canonical_name", "unknown") for doc in anchor_results]
        print(f"\n🕸️  [GRAPH RAG] Start: {len(anchor_results)} anchor tables found: {anchor_names}")


        # Phase A: process anchor nodes
        for doc in anchor_results:
            _process_single_doc(doc, final_schema_map, tables_to_fetch_names)

        # Phase B: Multi-Hop Expansion fetching neighbors based on Foreign Keys
        MAX_HOPS = 2
        for hop in range(MAX_HOPS):
            missing_tables = tables_to_fetch_names - set(final_schema_map.keys())
            
            if not missing_tables:
                break 
                
            print(f"🔗 [GRAPH RAG] Expansion Hop {hop+1}: Fetching {len(missing_tables)} linked tables: {list(missing_tables)[:5]}...")
            try:
                expansion_results = collection.get(ids=list(missing_tables))
                
                if expansion_results and expansion_results.get("metadatas"):
                    for meta in expansion_results["metadatas"]:
                        raw_json = meta.get("table_schema")
                        if raw_json:
                            _parse_and_add_to_map(raw_json, final_schema_map, tables_to_fetch_names)
            except Exception as e:
                print(f"⚠️ Expansion error at hop {hop+1}: {e}")

        # Phase C: Output Formatting
        trimmed_schema = list(final_schema_map.values())
        if not trimmed_schema:
            return empty_json

        json_output = json.dumps(trimmed_schema, indent=2)
        
        # Debugging payload size
        print(f"📊 [GRAPH RAG] Total tables: {len(trimmed_schema)} | Estimated payload tokens: {len(json_output)//4}")
        
        with open("debug_payload_v2.json", "w", encoding="utf-8") as f:
            f.write(json_output)
        print("💾 V2 Payload saved to 'debug_payload_v2.json'")

        return json_output

    except Exception as e:
        print(f"❌ CRITICAL ERROR IN TOOL: {e}")
        return empty_json
    
def resolve_entities_in_db(entities: List[str], k: int = 3) -> str:
    """Looks for text entities in the Vector DB of values and returns exact matches."""
    if not entities:
        return "Nessuna entità testuale trovata."
        
    try:
        vectorstore = Chroma(
            persist_directory=CHROMA_PATH, 
            embedding_function=EMBEDDING_FUNCTION, 
            collection_name=VALUE_COLLECTION_NAME
        )
        
        resolution_hints = []
        for entity in entities:
            # skip words that are too generic or short
            if len(entity.strip()) < 3:
                continue
                
            results = vectorstore.similarity_search(entity, k=k)
            if results:
                matches = [f"'{res.page_content}' (da {res.metadata.get('table_name')}.{res.metadata.get('column_name')})" for res in results]
                resolution_hints.append(f"- Se l'utente cerca '{entity}', usa ESATTAMENTE questi valori reali estratti dal DB: {', '.join(matches)}")
        
        if resolution_hints:
            return "\n".join(resolution_hints)
            
        return "Nessun match semantico esatto trovato per i valori testuali nel DB."
    except Exception as e:
        print(f"⚠️ Errore durante il Value Linking semantico: {e}")
        return "Impossibile recuperare i valori testuali."